language: ruby
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - ruby-head
  - jruby-18mode
  - jruby-19mode
  - rbx-18mode
  - rbx-19mode
  - ree
env:
  matrix:
    - "TASK=test"
    - "TASK=bench"
  allowed_failures:
    env:
      - "TASK=bench"
script: "bundle exec rake $TASK"
